const data = {
  products: [
    {
      name: 'Nike slim shirt',
      slug: 'nike-slim-shirt',
      category: 'shirts',
      image: '/images/p1.png',
      price: 120,
      brand: 'Nike',
      countInStock: 10,
      rating: 1,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Nike slim pants',
      slug: 'nike-slim-pants',
      category: 'pants',
      image: '/images/p2.png',
      price: 120,
      brand: 'Nike',
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality pants',
    },
    {
      name: 'Nike wide pants',
      slug: 'nike-wide-pants',
      category: 'pants',
      image: '/images/p3.png',
      price: 150,
      brand: 'Nike',
      countInStock: 10,
      rating: 4,
      numReviews: 10,
      description: 'high quality pants',
    },
    {
      name: 'Addidas wide pants',
      slug: 'Addidas-wide-pants',
      category: 'pants',
      image: '/images/p4.png',
      price: 170,
      brand: 'Addidas',
      countInStock: 10,
      rating: 3,
      numReviews: 10,
      description: 'high quality pants',
    },
    {
      name: 'Nike slim shirt',
      slug: 'nike-slim-shirt1',
      category: 'shirts',
      image: '/images/p1.png',
      price: 120,
      brand: 'Nike',
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Nike slim pants',
      slug: 'nike-slim-pants1',
      category: 'pants',
      image: '/images/p2.png',
      price: 120,
      brand: 'Nike',
      countInStock: 10,
      rating: 2,
      numReviews: 10,
      description: 'high quality pants',
    },
    {
      name: 'Nike wide pants',
      slug: 'nike-wide-pants1',
      category: 'pants',
      image: '/images/p3.png',
      price: 150,
      brand: 'Nike',
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality pants',
    },
    {
      name: 'Addidas wide pants',
      slug: 'Addidas-wide-pants1',
      category: 'pants',
      image: '/images/p4.png',
      price: 170,
      brand: 'Addidas',
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality pants',
    },
  ],
};
export default data;
